{{ $config := (datasource "config") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: grafana
    repo: kubes-terrafirma
    deployed-with: gomplate
  name: grafana-cm
  namespace: kube-system
data:
  grafana.ini: |
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins

    [server]
    http_port = 3000
    root_url = https://{{ $config.grafana.host }}

    [snapshots]
    external_enabled = false

    [log]
    mode = console
    level = info

    [dashboards.json]
    enabled = true
    path = /var/lib/grafana/dashboards

    [auth]
    disable_login_form = true

    [auth.anonymous]
    enabled = true
    org_role = Viewer

