---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: grafana
    repo: kubes-terrafirma
    deployed-with: gomplate
  name: grafana-dbsources
  namespace: kube-system
data:
  default.yaml: |
    apiVersion: 1

    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: true
      updateIntervalSeconds: 3600 #how often Grafana will scan for changed dashboards
      options:
        path: /var/lib/grafana/dashboards
