{{ $config := (datasource "config") }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: grafana
    deployed-with: gomplate
  name: grafana
  namespace: kube-system
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: "100%"
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      repo: kubes-terrafirma
  template:
    metadata:
      annotations:
        checksum/cm-config:  '{{ crypto.SHA1 (file.Read "yaml/grafana/config-map.yaml") }}'
        checksum/dashboards-config:  '{{ crypto.SHA1 (file.Read "yaml/grafana/dashboards-config-map.yaml") }}'
        checksum/datasources-config:  '{{ crypto.SHA1 (file.Read "yaml/grafana/datasources-config-map.yaml") }}'
        checksum/dbsources-config:  '{{ crypto.SHA1 (file.Read "yaml/grafana/dbsources-config-map.yaml") }}'
      labels:
        app: grafana
        repo: kubes-terrafirma
    spec:
      containers:
        - name: grafana
          image: "grafana/grafana:5.1.3"
          imagePullPolicy: Always
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Viewer"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
            - name: GF_AUTH_DISABLE_SIGNOUT_FORM
              value: "true"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 750m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 300Mi
          volumeMounts:
            - name: dashboard-volume
              mountPath: "/var/lib/grafana/dashboards"
            - name: datasource-volume
              mountPath: "/etc/grafana/provisioning/datasources"
            - name: dbsources-volume
              mountPath: "/etc/grafana/provisioning/dashboards"
      terminationGracePeriodSeconds: 30
      volumes:
        - name: dashboard-volume
          configMap:
            name: grafana-dashboards
        - name: datasource-volume
          configMap:
            name: grafana-datasources
        - name: dbsources-volume
          configMap:
            name: grafana-dbsources

