---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
    repo: kubes-terrafirma
    deployed-with: gomplate
  name: grafana-svc
  namespace: kube-system
spec:
  ports:
    - name: "http"
      port: 80
      protocol: TCP
      targetPort: 3001
  selector:
    app: grafana
    repo: kubes-terrafirma
  type: ClusterIP
