{{ $config := (datasource "config") }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuard
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  rules:
  - host: {{ $config.kuard.dnsRecord }}
    http:
      paths:
      - backend:
          serviceName: kuard
          servicePort: 8080
