---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    component: node-exporter
    repo: kubes-terrafirma
    deployed-with: kubectl
  name: prometheus-node-exporter-sa
  namespace: kube-system
