{{ $config := (datasource "config") }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-server-oidc
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app: prometheus-server-oidc
    repo: ops-kube-system
    deployed-with: gomplate
spec:
  rules:
  - host: {{ $config.prometheus.host }}
    http:
      paths:
      - backend:
          serviceName: prometheus-server-svc
          servicePort: 80
