---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    component: server
    repo: ops-kube-monitoring
    deployed-with: kubectl
  name: prometheus-server-svc
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus
    component: server
    repo: ops-kube-monitoring
  type: "ClusterIP"
