---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    component: server
    repo: ops-kube-monitoring
    deployed-with: kubectl
  name: prometheus-server-sa
  namespace: kube-system
