{{ $config := (datasource "config") }}

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
  labels:
    app: prometheus
    component: alertmanager
    repo: kubes-terrafirma
    deployed-with: gomplate
  name: prometheus-alertmanager-ingress
  namespace: kube-system
spec:
  rules:
    - host: {{ $config.alertmanager.host }}
      http:
        paths:
          - backend:
              serviceName: prometheus-alertmanager-svc
              servicePort: 80