---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    component: alertmanager
    repo: kubes-terrafirma
    deployed-with: gomplate
  name: prometheus-alertmanager-sa
  namespace: kube-system
