---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    component: alertmanager
    repo: kubes-terrafirma
    deployed-with: gomplate
  name: prometheus-alertmanager-svc
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9093
  selector:
    app: prometheus
    component: alertmanager
    repo: ops-kube-monitoring
  type: ClusterIP
