---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: thin
provisioner: kubernetes.io/vsphere-volume
parameters:
  datastore: KUB_vnx5600_aumelesx_kubernetes_01
  diskformat: thin
  fstype: ext4
